### ISSUE TITLE
error: no match for 'operator>>' (operand types are 'const QDBusArgument' and 'DataTransferInfo')

### ISSUE THREAD

**Issue by szotsaki** [Elv13/libringqt#2]
The following error happens during compiling. Quite a lengthy one but in the first lines lie the error.

```
[   88s] [ 33%] Building CXX object CMakeFiles/ringqt.dir/src/ringdevice.cpp.o
[   88s] /usr/bin/c++  -DENABLE_VIDEO=true -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_NO_DEBUG -D__ANDROID__=1 -Dringqt_EXPORTS -I/home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build -I/home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50 -I/home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/ringqt_autogen/include -I/usr/include/dring -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtDBus -I/home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src -I/home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/private  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -DNDEBUG -O2 -g -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -Wall -Wextra -Wmissing-declarations -Wmissing-noreturn -Wpointer-arith -Wcast-align -Wwrite-strings -Wformat-nonliteral -Wformat-security -Wswitch-enum -Winit-self -Wmissing-include-dirs -Wundef -Wmissing-format-attribute -Wno-reorder -Wunused -Wuninitialized -Woverloaded-virtual -Wunused-value -Wnonnull -Wsequence-point -Wsizeof-pointer-memaccess -Wvarargs -Wno-unused-function -Wno-attributes -Wno-missing-include-dirs -Wno-unknown-pragmas -fPIC -std=gnu++14 -o CMakeFiles/ringqt.dir/src/ringdevice.cpp.o -c /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp
[   90s] In file included from /usr/include/qt5/QtDBus/QtDBus:7:0,
[   90s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   90s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   90s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h: In instantiation of 'T qdbus_cast(const QDBusArgument&, T*) [with T = DataTransferInfo]':
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:180:29:   required from 'T qdbus_cast(const QVariant&, T*) [with T = DataTransferInfo]'
[   91s] /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:118:84:   required from here
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:168:9: error: no match for 'operator>>' (operand types are 'const QDBusArgument' and 'DataTransferInfo')
[   91s]      arg >> item;
[   91s]      ~~~~^~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:121:26: note: candidate: const QDBusArgument& QDBusArgument::operator>>(uchar&) const
[   91s]      const QDBusArgument &operator>>(uchar &arg) const;
[   91s]                           ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:121:26: note:   no known conversion for argument 1 from 'DataTransferInfo' to 'uchar& {aka unsigned char&}'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:122:26: note: candidate: const QDBusArgument& QDBusArgument::operator>>(bool&) const
[   91s]      const QDBusArgument &operator>>(bool &arg) const;
[   91s]                           ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:122:26: note:   no known conversion for argument 1 from 'DataTransferInfo' to 'bool&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:123:26: note: candidate: const QDBusArgument& QDBusArgument::operator>>(short int&) const
[   91s]      const QDBusArgument &operator>>(short &arg) const;
[   91s]                           ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:123:26: note:   no known conversion for argument 1 from 'DataTransferInfo' to 'short int&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:124:26: note: candidate: const QDBusArgument& QDBusArgument::operator>>(ushort&) const
[   91s]      const QDBusArgument &operator>>(ushort &arg) const;
[   91s]                           ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:124:26: note:   no known conversion for argument 1 from 'DataTransferInfo' to 'ushort& {aka short unsigned int&}'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:125:26: note: candidate: const QDBusArgument& QDBusArgument::operator>>(int&) const
[   91s]      const QDBusArgument &operator>>(int &arg) const;
[   91s]                           ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:125:26: note:   no known conversion for argument 1 from 'DataTransferInfo' to 'int&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:126:26: note: candidate: const QDBusArgument& QDBusArgument::operator>>(uint&) const
[   91s]      const QDBusArgument &operator>>(uint &arg) const;
[   91s]                           ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:126:26: note:   no known conversion for argument 1 from 'DataTransferInfo' to 'uint& {aka unsigned int&}'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:127:26: note: candidate: const QDBusArgument& QDBusArgument::operator>>(qlonglong&) const
[   91s]      const QDBusArgument &operator>>(qlonglong &arg) const;
[   91s]                           ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:127:26: note:   no known conversion for argument 1 from 'DataTransferInfo' to 'qlonglong& {aka long long int&}'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:128:26: note: candidate: const QDBusArgument& QDBusArgument::operator>>(qulonglong&) const
[   91s]      const QDBusArgument &operator>>(qulonglong &arg) const;
[   91s]                           ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:128:26: note:   no known conversion for argument 1 from 'DataTransferInfo' to 'qulonglong& {aka long long unsigned int&}'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:129:26: note: candidate: const QDBusArgument& QDBusArgument::operator>>(double&) const
[   91s]      const QDBusArgument &operator>>(double &arg) const;
[   91s]                           ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:129:26: note:   no known conversion for argument 1 from 'DataTransferInfo' to 'double&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:130:26: note: candidate: const QDBusArgument& QDBusArgument::operator>>(QString&) const
[   91s]      const QDBusArgument &operator>>(QString &arg) const;
[   91s]                           ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:130:26: note:   no known conversion for argument 1 from 'DataTransferInfo' to 'QString&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:131:26: note: candidate: const QDBusArgument& QDBusArgument::operator>>(QDBusVariant&) const
[   91s]      const QDBusArgument &operator>>(QDBusVariant &arg) const;
[   91s]                           ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:131:26: note:   no known conversion for argument 1 from 'DataTransferInfo' to 'QDBusVariant&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:132:26: note: candidate: const QDBusArgument& QDBusArgument::operator>>(QDBusObjectPath&) const
[   91s]      const QDBusArgument &operator>>(QDBusObjectPath &arg) const;
[   91s]                           ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:132:26: note:   no known conversion for argument 1 from 'DataTransferInfo' to 'QDBusObjectPath&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:133:26: note: candidate: const QDBusArgument& QDBusArgument::operator>>(QDBusSignature&) const
[   91s]      const QDBusArgument &operator>>(QDBusSignature &arg) const;
[   91s]                           ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:133:26: note:   no known conversion for argument 1 from 'DataTransferInfo' to 'QDBusSignature&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:134:26: note: candidate: const QDBusArgument& QDBusArgument::operator>>(QDBusUnixFileDescriptor&) const
[   91s]      const QDBusArgument &operator>>(QDBusUnixFileDescriptor &arg) const;
[   91s]                           ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:134:26: note:   no known conversion for argument 1 from 'DataTransferInfo' to 'QDBusUnixFileDescriptor&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:135:26: note: candidate: const QDBusArgument& QDBusArgument::operator>>(QStringList&) const
[   91s]      const QDBusArgument &operator>>(QStringList &arg) const;
[   91s]                           ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:135:26: note:   no known conversion for argument 1 from 'DataTransferInfo' to 'QStringList&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:136:26: note: candidate: const QDBusArgument& QDBusArgument::operator>>(QByteArray&) const
[   91s]      const QDBusArgument &operator>>(QByteArray &arg) const;
[   91s]                           ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:136:26: note:   no known conversion for argument 1 from 'DataTransferInfo' to 'QByteArray&'
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:43:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qdatastream.h:370:21: note: candidate: template<class E> QDataStream& operator>>(QDataStream&, QFlags<T>&)
[   91s]  inline QDataStream &operator>>(QDataStream &s, QFlags<Enum> &e)
[   91s]                      ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qdatastream.h:370:21: note:   template argument deduction/substitution failed:
[   91s] In file included from /usr/include/qt5/QtDBus/QtDBus:7:0,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:168:9: not[   81.261164] serial8250: too much work for irq4
[   91s] e:   'DataTransferInfo' is not derived from 'QFlags<T>'
[   91s]      arg >> item;
[   91s]      ~~~~^~~~~~~
[   91s] In file included from /usr/include/qt5/QtCore/qstring.h:48:0,
[   91s]                  from /usr/include/qt5/QtCore/qobject.h:47,
[   91s]                  from /usr/include/qt5/QtCore/QObject:1,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:20:
[   91s] /usr/include/qt5/QtCore/qchar.h:606:28: note: candidate: QDataStream& operator>>(QDataStream&, QChar&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QChar &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qchar.h:606:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/qstring.h:49:0,
[   91s]                  from /usr/include/qt5/QtCore/qobject.h:47,
[   91s]                  from /usr/include/qt5/QtCore/QObject:1,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:20:
[   91s] /usr/include/qt5/QtCore/qbytearray.h:679:28: note: candidate: QDataStream& operator>>(QDataStream&, QByteArray&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QByteArray &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qbytearray.h:679:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/qobject.h:47:0,
[   91s]                  from /usr/include/qt5/QtCore/QObject:1,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:20:
[   91s] /usr/include/qt5/QtCore/qstring.h:1400:28: note: candidate: QDataStream& operator>>(QDataStream&, QString&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QString &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qstring.h:1400:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/qstringlist.h:47:0,
[   91s]                  from /usr/include/qt5/QtCore/qlist.h:1094,
[   91s]                  from /usr/include/qt5/QtCore/qobject.h:49,
[   91s]                  from /usr/include/qt5/QtCore/QObject:1,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:20:
[   91s] /usr/include/qt5/QtCore/qregexp.h:125:28: note: candidate: QDataStream& operator>>(QDataStream&, QRegExp&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &in, QRegExp &regExp);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qregexp.h:125:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/qlocale.h:43:0,
[   91s]                  from /usr/include/qt5/QtCore/qtextstream.h:46,
[   91s]                  from /usr/include/qt5/QtCore/qdebug.h:49,
[   91s]                  from /usr/include/qt5/QtCore/QDebug:1,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/typedefs.h:26,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.h:20,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:22:
[   91s] /usr/include/qt5/QtCore/qvariant.h:539:28: note: candidate: QDataStream& operator>>(QDataStream&, QVariant&)
[   91s]  Q_CORE_EXPORT QDataStream& operator>> (QDataStream& s, QVariant& p);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qvariant.h:539:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] /usr/include/qt5/QtCore/qvariant.h:541:28: note: candidate: QDataStream& operator>>(QDataStream&, QVariant::Type&)
[   91s]  Q_CORE_EXPORT QDataStream& operator>> (QDataStream& s, QVariant::Type& p);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qvariant.h:541:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/qtextstream.h:46:0,
[   91s]                  from /usr/include/qt5/QtCore/qdebug.h:49,
[   91s]                  from /usr/include/qt5/QtCore/QDebug:1,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/typedefs.h:26,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.h:20,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:22:
[   91s] /usr/include/qt5/QtCore/qlocale.h:1120:28: note: candidate: QDataStream& operator>>(QDataStream&, QLocale&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QLocale &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qlocale.h:1120:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/qdebug.h:49:0,
[   91s]                  from /usr/include/qt5/QtCore/QDebug:1,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/typedefs.h:26,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.h:20,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:22:
[   91s] /usr/include/qt5/QtCore/qtextstream.h:226:21: note: candidate: QTextStream& operator>>(QTextStream&, QTextStreamFunction)
[   91s]  inline QTextStream &operator>>(QTextStream &s, QTextStreamFunction f)
[   91s]                      ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qtextstream.h:226:21: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QTextStream&'
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:23:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qbitarray.h:165:28: note: candidate: QDataStream& operator>>(QDataStream&, QBitArray&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QBitArray &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qbitarray.h:165:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:43:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qdatastream.h:374:21: note: candidate: template<class T> QDataStream& operator>>(QDataStream&, QList<T>&)
[   91s]  inline QDataStream &operator>>(QDataStream &s, QList<T> &l)
[   91s]                      ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qdatastream.h:374:21: note:   template argument deduction/substitution failed:
[   91s] In file included from /usr/include/qt5/QtDBus/QtDBus:7:0,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:168:9: note:   'DataTransferInfo' is not derived from 'QList<T>'
[   91s]      arg >> item;
[   91s]      ~~~~^~~~~~~
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:43:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abui[   81.368492] serial8250: too much work for irq4
[   91s] ld/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qdatastream.h:386:21: note: candidate: template<class T> QDataStream& operator>>(QDataStream&, QLinkedList<T>&)
[   91s]  inline QDataStream &operator>>(QDataStream &s, QLinkedList<T> &l)
[   91s]                      ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qdatastream.h:386:21: note:   template argument deduction/substitution failed:
[   91s] In file included from /usr/include/qt5/QtDBus/QtDBus:7:0,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:168:9: note:   'DataTransferInfo' is not derived from 'QLinkedList<T>'
[   91s]      arg >> item;
[   91s]      ~~~~^~~~~~~
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:43:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qdatastream.h:398:21: note: candidate: template<class T> QDataStream& operator>>(QDataStream&, QVector<T>&)
[   91s]  inline QDataStream &operator>>(QDataStream &s, QVector<T> &v)
[   91s]                      ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qdatastream.h:398:21: note:   template argument deduction/substitution failed:
[   91s] In file included from /usr/include/qt5/QtDBus/QtDBus:7:0,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:168:9: note:   'DataTransferInfo' is not derived from 'QVector<T>'
[   91s]      arg >> item;
[   91s]      ~~~~^~~~~~~
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:43:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qdatastream.h:410:21: note: candidate: template<class T> QDataStream& operator>>(QDataStream&, QSet<T>&)
[   91s]  inline QDataStream &operator>>(QDataStream &s, QSet<T> &set)
[   91s]                      ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qdatastream.h:410:21: note:   template argument deduction/substitution failed:
[   91s] In file included from /usr/include/qt5/QtDBus/QtDBus:7:0,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:168:9: note:   'DataTransferInfo' is not derived from 'QSet<T>'
[   91s]      arg >> item;
[   91s]      ~~~~^~~~~~~
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:43:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qdatastream.h:422:21: note: candidate: template<class Key, class T> QDataStream& operator>>(QDataStream&, QHash<K, V>&)
[   91s]  inline QDataStream &operator>>(QDataStream &s, QHash<Key, T> &hash)
[   91s]                      ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qdatastream.h:422:21: note:   template argument deduction/substitution failed:
[   91s] In file included from /usr/include/qt5/QtDBus/QtDBus:7:0,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:168:9: note:   'DataTransferInfo' is not derived from 'QHash<K, V>'
[   91s]      arg >> item;
[   91s]      ~~~~^~~~~~~
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:43:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qdatastream.h:434:21: note: candidate: template<class Key, class T> QDataStream& operator>>(QDataStream&, QMap<K, V>&)
[   91s]  inline QDataStream &operator>>(QDataStream &s, QMap<Key, T> &map)
[   91s]                      ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qdatastream.h:434:21: note:   template argument deduction/substitution failed:
[   91s] In file included from /usr/include/qt5/QtDBus/QtDBus:7:0,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:168:9: note:   'DataTransferInfo' is not derived from 'QMap<K, V>'
[   91s]      arg >> item;
[   91s]      ~~~~^~~~~~~
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:43:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qdatastream.h:447:21: note: candidate: template<class T1, class T2> QDataStream& operator>>(QDataStream&, QPair<T1, T2>&)
[   91s]  inline QDataStream& operator>>(QDataStream& s, QPair<T1, T2>& p)
[   91s]                      ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qdatastream.h:447:21: note:   template argument deduction/substitution failed:
[   91s] In file included from /usr/include/qt5/QtDBus/QtDBus:7:0,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:168:9: n[   81.466074] serial8250: too much work for irq4
[   91s] ote:   'DataTransferInfo' is not derived from 'QPair<T1, T2>'
[   91s]      arg >> item;
[   91s]      ~~~~^~~~~~~
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:44:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qdatetime.h:397:28: note: candidate: QDataStream& operator>>(QDataStream&, QDate&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QDate &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qdatetime.h:397:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] /usr/include/qt5/QtCore/qdatetime.h:399:28: note: candidate: QDataStream& operator>>(QDataStream&, QTime&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QTime &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qdatetime.h:399:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] /usr/include/qt5/QtCore/qdatetime.h:401:28: note: candidate: QDataStream& operator>>(QDataStream&, QDateTime&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QDateTime &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qdatetime.h:401:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:49:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qeasingcurve.h:136:28: note: candidate: QDataStream& operator>>(QDataStream&, QEasingCurve&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QEasingCurve &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qeasingcurve.h:136:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/qlibraryinfo.h:45:0,
[   91s]                  from /usr/include/qt5/QtCore/QtCore:90,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qversionnumber.h:291:39: note: candidate: QDataStream& operator>>(QDataStream&, QVersionNumber&)
[   91s]      friend Q_CORE_EXPORT QDataStream& operator>>(QDataStream &in, QVersionNumber &version);
[   91s]                                        ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qversionnumber.h:291:39: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/qline.h:43:0,
[   91s]                  from /usr/include/qt5/QtCore/QtCore:91,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qpoint.h:113:28: note: candidate: QDataStream& operator>>(QDataStream&, QPoint&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QPoint &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qpoint.h:113:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] /usr/include/qt5/QtCore/qpoint.h:278:28: note: candidate: QDataStream& operator>>(QDataStream&, QPointF&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QPointF &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qpoint.h:278:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:91:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qline.h:208:28: note: candidate: QDataStream& operator>>(QDataStream&, QLine&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QLine &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qline.h:208:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] /usr/include/qt5/QtCore/qline.h:429:28: note: candidate: QDataStream& operator>>(QDataStream&, QLineF&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QLineF &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qline.h:429:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:98:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qmargins.h:95:28: note: candidate: QDataStream& operator>>(QDataStream&, QMargins&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QMargins &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qmargins.h:95:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] /usr/include/qt5/QtCore/qmargins.h:328:28: note: candidate: QDataStream& operator>>(QDataStream&, QMarginsF&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QMarginsF &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qmargins.h:328:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/qrect.h:44:0,
[   91s]                  from /usr/include/qt5/QtCore/QtCore:128,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qsize.h:109:28: note: candidate: QDataStream& operator>>(QDataStream&, QSize&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QSize &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qsize.h:109:28: note:   no known conversion for argument 1 from 'cons[   81.561880] serial8250: too much work for irq4
[   91s] t QDBusArgument' to 'QDataStream&'
[   91s] /usr/include/qt5/QtCore/qsize.h:277:28: note: candidate: QDataStream& operator>>(QDataStream&, QSizeF&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QSizeF &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qsize.h:277:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:128:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qrect.h:177:28: note: candidate: QDataStream& operator>>(QDataStream&, QRect&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QRect &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qrect.h:177:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] /usr/include/qt5/QtCore/qrect.h:637:28: note: candidate: QDataStream& operator>>(QDataStream&, QRectF&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QRectF &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qrect.h:637:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:131:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qregularexpression.h:165:28: note: candidate: QDataStream& operator>>(QDataStream&, QRegularExpression&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &in, QRegularExpression &re);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qregularexpression.h:165:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:183:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qtimezone.h:181:28: note: candidate: QDataStream& operator>>(QDataStream&, QTimeZone&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &ds, QTimeZone &tz);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qtimezone.h:181:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:188:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/qurl.h:411:28: note: candidate: QDataStream& operator>>(QDataStream&, QUrl&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QUrl &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/qurl.h:411:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtCore/QtCore:190:0,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBusDepends:3,
[   91s]                  from /usr/include/qt5/QtDBus/QtDBus:3,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtCore/quuid.h:228:28: note: candidate: QDataStream& operator>>(QDataStream&, QUuid&)
[   91s]  Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QUuid &);
[   91s]                             ^~~~~~~~
[   91s] /usr/include/qt5/QtCore/quuid.h:228:28: note:   no known conversion for argument 1 from 'const QDBusArgument' to 'QDataStream&'
[   91s] In file included from /usr/include/qt5/QtDBus/QtDBus:7:0,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/build/configurationmanager_dbus_interface.h:21,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/dbus/configurationmanager.h:24,
[   91s]                  from /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180417.19a4c50/src/ringdevice.cpp:24:
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:197:36: note: candidate: const QDBusArgument& operator>>(const QDBusArgument&, QVariant&)
[   91s]  Q_DBUS_EXPORT const QDBusArgument &operator>>(const QDBusArgument &a, QVariant &v);
[   91s]                                     ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:197:36: note:   no known conversion for argument 2 from 'DataTransferInfo' to 'QVariant&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:202:36: note: candidate: const QDBusArgument& operator>>(const QDBusArgument&, QDate&)
[   91s]  Q_DBUS_EXPORT const QDBusArgument &operator>>(const QDBusArgument &a, QDate &date);
[   91s]                                     ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:202:36: note:   no known conversion for argument 2 from 'DataTransferInfo' to 'QDate&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:205:36: note: candidate: const QDBusArgument& operator>>(const QDBusArgument&, QTime&)
[   91s]  Q_DBUS_EXPORT const QDBusArgument &operator>>(const QDBusArgument &a, QTime &time);
[   91s]                                     ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:205:36: note:   no known conversion for argument 2 from 'DataTransferInfo' to 'QTime&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:208:36: note: candidate: const QDBusArgument& operator>>(const QDBusArgument&, QDateTime&)
[   91s]  Q_DBUS_EXPORT const QDBusArgument &operator>>(const QDBusArgument &a, QDateTime &dt);
[   91s]                                     ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:208:36: note:   no known conversion for argument 2 from 'DataTransferInfo' to 'QDateTime&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:211:36: note: candidate: const QDBusArgument& operator>>(const QDBusArgument&, QRect&)
[   91s]  Q_DBUS_EXPORT const QDBusArgument &operator>>(const QDBusArgument &a, QRect &rect);
[   91s]                                     ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:211:36: note:   no known conversion for argument 2 from 'DataTransferInfo' to 'QRect&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:214:36: note: candidate: const QDBusArgument& operator>>(const QDBusArgument&, QRectF&)
[   91s]  Q_DBUS_EXPORT const QDBusArgument &operator>>(const QDBusArgument &a, QRectF &rect);
[   91s]                                     ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:214:36: note:   no known conversion for argument 2 from 'DataTransferInfo' to 'QRectF&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:217:36: note: candidate: const QDBusArgument& operator>>(const QDBusArgument&, QSize&)
[   91s]  Q_DBUS_EXPORT const QDBusArgument &operator>>(const QDBusArgument &a, QSize &size);
[   91s]                                     ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusa[   81.659122] serial8250: too much work for irq4
[   91s] rgument.h:217:36: note:   no known conversion for argument 2 from 'DataTransferInfo' to 'QSize&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:220:36: note: candidate: const QDBusArgument& operator>>(const QDBusArgument&, QSizeF&)
[   91s]  Q_DBUS_EXPORT const QDBusArgument &operator>>(const QDBusArgument &a, QSizeF &size);
[   91s]                                     ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:220:36: note:   no known conversion for argument 2 from 'DataTransferInfo' to 'QSizeF&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:223:36: note: candidate: const QDBusArgument& operator>>(const QDBusArgument&, QPoint&)
[   91s]  Q_DBUS_EXPORT const QDBusArgument &operator>>(const QDBusArgument &a, QPoint &pt);
[   91s]                                     ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:223:36: note:   no known conversion for argument 2 from 'DataTransferInfo' to 'QPoint&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:226:36: note: candidate: const QDBusArgument& operator>>(const QDBusArgument&, QPointF&)
[   91s]  Q_DBUS_EXPORT const QDBusArgument &operator>>(const QDBusArgument &a, QPointF &pt);
[   91s]                                     ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:226:36: note:   no known conversion for argument 2 from 'DataTransferInfo' to 'QPointF&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:229:36: note: candidate: const QDBusArgument& operator>>(const QDBusArgument&, QLine&)
[   91s]  Q_DBUS_EXPORT const QDBusArgument &operator>>(const QDBusArgument &a, QLine &line);
[   91s]                                     ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:229:36: note:   no known conversion for argument 2 from 'DataTransferInfo' to 'QLine&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:232:36: note: candidate: const QDBusArgument& operator>>(const QDBusArgument&, QLineF&)
[   91s]  Q_DBUS_EXPORT const QDBusArgument &operator>>(const QDBusArgument &a, QLineF &line);
[   91s]                                     ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:232:36: note:   no known conversion for argument 2 from 'DataTransferInfo' to 'QLineF&'
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:250:29: note: candidate: template<template<class> class Container, class T> const QDBusArgument& operator>>(const QDBusArgument&, Container<T>&)
[   91s]  inline const QDBusArgument &operator>>(const QDBusArgument &arg, Container<T> &list)
[   91s]                              ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:250:29: note:   template argument deduction/substitution failed:
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:168:9: note:   'DataTransferInfo' is not derived from 'Container<T>'
[   91s]      arg >> item;
[   91s]      ~~~~^~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:279:29: note: candidate: template<class T> const QDBusArgument& operator>>(const QDBusArgument&, QList<T>&)
[   91s]  inline const QDBusArgument &operator>>(const QDBusArgument &arg, QList<T> &list)
[   91s]                              ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:279:29: note:   template argument deduction/substitution failed:
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:168:9: note:   'DataTransferInfo' is not derived from 'QList<T>'
[   91s]      arg >> item;
[   91s]      ~~~~^~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:324:29: note: candidate: template<class Key, class T> const QDBusArgument& operator>>(const QDBusArgument&, QMap<K, V>&)
[   91s]  inline const QDBusArgument &operator>>(const QDBusArgument &arg, QMap<Key, T> &map)
[   91s]                              ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:324:29: note:   template argument deduction/substitution failed:
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:168:9: note:   'DataTransferInfo' is not derived from 'QMap<K, V>'
[   91s]      arg >> item;
[   91s]      ~~~~^~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:373:29: note: candidate: template<class Key, class T> const QDBusArgument& operator>>(const QDBusArgument&, QHash<K, V>&)
[   91s]  inline const QDBusArgument &operator>>(const QDBusArgument &arg, QHash<Key, T> &map)
[   91s]                              ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:373:29: note:   template argument deduction/substitution failed:
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:168:9: note:   'DataTransferInfo' is not derived from 'QHash<K, V>'
[   91s]      arg >> item;
[   91s]      ~~~~^~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:413:29: note: candidate: template<class T1, class T2> const QDBusArgument& operator>>(const QDBusArgument&, QPair<T1, T2>&)
[   91s]  inline const QDBusArgument &operator>>(const QDBusArgument &arg, QPair<T1, T2> &pair)
[   91s]                              ^~~~~~~~
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:413:29: note:   template argument deduction/substitution failed:
[   91s] /usr/include/qt5/QtDBus/qdbusargument.h:168:9: note:   'DataTransferInfo' is not derived from 'QPair<T1, T2>'
[   91s]      arg >> item;
[   91s]      ~~~~^~~~~~~
```

**Comment by abouvier** [comment]
This error is present since the ring-daemon (dring) version ~20180216.

**Comment by Elv13** [comment]
done, thanks for caring!

And yes, random upstream API breaks without version change are not cool... Now `libringqt` compiles with master, but not with officially released versions. I don't want to add `#if` for every breaking changes because otherwise they become untested.

Btw, a precompiled versions is here http://lvindustries.net:8080/

**Comment by szotsaki** [comment]
Hmm, unfortunately with the latest change (cebabca98047b11c26513800ffcda0a8c915ee59) it still happens:

```
[   55s] /home/abuild/rpmbuild/BUILD/libringqt-1.0.0.20180419.cebabca/build/configurationmanager_dbus_interface.h:118:84:   required from here
[   55s] /usr/include/qt5/QtDBus/qdbusargument.h:168:9: error: no match for 'operator>>' (operand types are 'const QDBusArgument' and 'DataTransferInfo')
[   55s]      arg >> item;
[   55s]      ~~~~^~~~~~~
```

**Comment by Elv13** [comment]
Indeed. Yesterday commit only fixed the "single executable" mode. The dbus client-server mode was indeed still broken. I usually prefer the single executable mode because it tend to keep working no matter what they change (umm, like this...). It's also a little more secure because it supports binary hardening and the client/server mode "ring daemon" isn't compiled correctly for it.

So I fixed this issue, but I advice to to use the library mode instead of the dbus mode. The appimage is probably the most stable version because it uses known working versions of all the ring-daemon dependencies. It will eventually have full sandboxing, but that's not enabled yet. If you prefer to roll your own, there is a docker file for it:

https://github.com/ring-project/ring-kde-appimage-builder/tree/gentoo_base
